name: Auto Tag Version

on:
  push:
    branches:
      - main

jobs:
  tag-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bump2version

      - name: Bump version and push tag
        run: |
          # Assuming version information is in setup.py
          VERSION=$(python setup.py --version)
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git tag -a "v$VERSION" -m "Release version $VERSION"
          git push origin --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
