name: Python Package

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Set Git Identity
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Auto bump version
        if: github.ref == 'refs/heads/main'  # Run only on main branch
        run: |
          bump2version patch --config-file .bumpversion.cfg

      - name: Lint with Flake8
        run: |
          pip install flake8
          flake8 ./lib-version

      - name: Build and publish to PyPI
        if: startsWith(github.ref, 'refs/tags/v')  # Only runs if the push is a tag starting with 'v'
        run: |
          pip install build twine
          python -m build
          python -m twine upload dist/* --skip-existing
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        continue-on-error: false  # Ensure that errors in this step fail the workflow

