name: Python Package

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Set Git Identity
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Extract Version from Tag
        id: get_version
        run: echo "::set-output name=VERSION::${GITHUB_REF#refs/tags/v}"

      - name: Update version.py and pyproject.toml
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "Updating version.py with version ${{ steps.get_version.outputs.VERSION }}"
          echo "__version__ = '${{ steps.get_version.outputs.VERSION }}'" > lib_version_URLPhishing/version.py
          poetry version ${{ steps.get_version.outputs.VERSION }}
          git add lib_version_URLPhishing/version.py pyproject.toml
          git commit -m "Update version to ${{ steps.get_version.outputs.VERSION }}"
          git push

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      - name: Install dependencies
        run: poetry install

      - name: Lint with Flake8
        run: poetry run flake8 ./lib_version_URLPhishing

      - name: Fetch latest changes
        run: git fetch origin main && git reset --hard origin/main

      - name: Build and publish to PyPI
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          poetry build
          poetry publish -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_PASSWORD }}

      - name: Install pdoc
        run: pip install pdoc3

      - name: Generate documentation
        run: pdoc --html lib_version_URLPhishing --output-dir docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/lib_version_URLPhishing
