name: Python Package

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r test-requirements.txt

      - name: Lint with Flake8
        run: |
          pip install flake8
          flake8 ./src

      - name: Test with pytest
        run: |
          pip install pytest
          pytest

      - name: Build and publish to PyPI
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          pip install build twine
          python -m build
          python -m twine upload dist/* --skip-existing
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
